# Generated by Django 4.2.7 on 2025-12-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableProcessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_group', models.CharField(max_length=100, verbose_name='업무그룹')),
                ('db_table_name', models.CharField(max_length=100, verbose_name='테이블명')),
                ('process_order', models.IntegerField(verbose_name='처리 순서')),
                ('table_prompt', models.TextField(blank=True, null=True, verbose_name='테이블 프롬프트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_configs', to='core.declaration', verbose_name='신고서')),
                ('service_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_configs', to='core.serviceuser', verbose_name='서비스 사용자')),
            ],
            options={
                'verbose_name': '테이블 처리 설정',
                'verbose_name_plural': '테이블 처리 설정',
                'db_table': 'table_process_configs',
                'ordering': ['declaration', 'process_order'],
                'unique_together': {('declaration', 'service_user', 'db_table_name')},
            },
        ),
        migrations.AddField(
            model_name='mappinginfo',
            name='table_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.tableprocessconfig', verbose_name='테이블 처리 설정'),
        ),
    ]
